# Generated by Django 4.1.7 on 2023-03-03 04:29

import apps.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_image_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0, upload_to=apps.course.models.image_path),
            preserve_default=False,
        ),
    ]
