# Generated by Django 4.1.7 on 2023-03-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0004_course_author_soldcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile'),
        ),
    ]
