# Generated by Django 4.1.7 on 2023-03-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_role'),
        ('course', '0005_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldcourse',
            name='profile',
            field=models.ForeignKey(limit_choices_to={'role': 0}, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
